### ISSUE TITLE
Where should mouser_api_keys.yaml be located for it to be detected by an API call?

### ISSUE THREAD

**Issue by ghost** [sparkmicro/mouser-api#1]
"create a file named mouser_api_keys.yaml with the order API key on the first line and the part API key on a second line."

I have done this but am now confused on where to place this file in my windows directory. When I call the API i get "[ERROR] API Keys File "mouser_api_keys.yaml" Not Found"

**Comment by ghost** [comment]
Nevermind! I put that file in the project directory, silly me!

**Comment by eeintech** [comment]
Glad you sorted it out @nickryt !
