### ISSUE TITLE
Pypi repository-link links to outdated git-repo

### ISSUE THREAD

**Issue by gituser789** [sparkmicro/mouser-api#2]
**Describing the problem**
Visiting https://pypi.org/project/mouser/ and using link to git repo results in Error 404.
![image](https://user-images.githubusercontent.com/62549000/201053432-2e4bcd74-175b-46a2-94dc-f0d1a86393e1.png)

**How to solve**
Link needs to be updated to new repository name `https://github.com/sparkmicro/mouser-api`

**Comment by eeintech** [comment]
Hello @gituser789, thanks for spotting this issue! It is fixed now in `0.1.2` :smiley:
