### ISSUE TITLE
Issues Authenticating

### ISSUE THREAD

**Issue by cmcewenkcnsc** [sparkmicro/mouser-api#3]
It doesn't appear to be authenticating my mouser key. I tried entering the keys in manually to the Mouser Test.py file on lines 22 & 23 as well as putting the mouser_api_keys.yaml file in the directory.  I have modified the test_mouser.py by adding the following code at the end:

test_version()
test_search_partnumber()

I know it is going to be a me not doing something right on this one, but help would be greatly appreciated. 

Thank you!

**Comment by eeintech** [comment]
Hello @cmcewenkcnsc 

On which platform are you running it?

Can you please share the output of:
``` bash
echo $MOUSER_PART_API_KEY
```

and:
``` bash
cat mouser_api_keys.yaml
```

What does `test_search_partnumber()` returns? Please share the traceback, thanks.

**Comment by cmcewenkcnsc** [comment]
I am using anaconda to run it using python 3.9.13 using windows

the echo just returns

$MOUSER_PART_API_KEY

cat is 

Hidden Key
Hidden Key

when I run test_seach_partnumber() I get:
Traceback (most recent call last):
  File "C:\Users\U6\Downloads\mouser-api-main\mouser-api-main\tests\test_mouser.py", line 26, in <module>
    test_search_partnumber()
  File "C:\Users\U6\Downloads\mouser-api-main\mouser-api-main\tests\test_mouser.py", line 14, in test_search_partnumber
    request = MouserPartSearchRequest('partnumber')
  File "C:\Users\U6\Anaconda3\lib\site-packages\mouser\base.py", line 131, in __init__
    super().__init__(url, method, file_keys, *args)
  File "C:\Users\U6\Anaconda3\lib\site-packages\mouser\base.py", line 68, in __init__
    raise FileNotFoundError('API Keys Are Missing')
FileNotFoundError: API Keys Are Missing

**Comment by eeintech** [comment]
@cmcewenkcnsc So your API key file is fine, please delete the entries in your previous message so nobody else can get them from you (eg. never share the full key publicly).

The error is telling you it is not finding the path to this file, so if you want to reuse my test methods, follow those steps: 

1. Edit the `tests/test_mouser.py` file with:
``` python
from mouser import __version__
from mouser.api import MouserPartSearchRequest


def test_version():
    assert __version__ == '0.1.2'


def test_search_partnumber(file_keys='mouser_api_keys.yaml'):

    partnumber = 'DMP2066LSN-7'

    request = MouserPartSearchRequest('partnumber', file_keys=file_keys)
    assert request.api_url == 'https://api.mouser.com/api/v1.0/search/partnumber'

    success = request.part_search(partnumber)
    assert success is True

    part = request.get_clean_response()
    assert part['Manufacturer'] == 'Diodes Incorporated'
    assert part['ManufacturerPartNumber'] == 'DMP2066LSN-7'
    assert part['MouserPartNumber'] == '621-DMP2066LSN-7'

if __name__ == '__main__':
    test_version()
    test_search_partnumber(file_keys='/home/user/<path-to-file>/mouser_api_keys.yaml')
```
2. Replace `file_keys='/home/user/<path-to-file>/mouser_api_keys.yaml'` with the actual path to the `mouser_api_keys.yaml` file on your machine
3. Then run `python tests/test_mouser.py`

Now as I help you with this I realized that if someone would run the `mouser search partnumber --number XXX` command outside of the folder containing the `mouser_api_keys.yaml` file it would return the same error. This is why environment variable work better :smile: so in the next update I will make sure this is a. covered in the README b. add an option to specify the path the API key file in the CLI.

**Comment by cmcewenkcnsc** [comment]
I believe that fixed it. I have internal firewall issues that I am getting now with SSLErrors. I will mark this as complete as I am almost certain I have to figure out this next one internally unfortunately. 

requests.exceptions.SSLError: HTTPSConnectionPool(host='api.mouser.com', port=443): Max retries exceeded with url: /api/v1.0/search/partnumber?apiKey=My_Hidden_Key (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

**Comment by eeintech** [comment]
Umm yeah not sure what's happening here... Lots of good stuff to check here: https://stackoverflow.com/a/72666365/12794913

**Comment by cmcewenkcnsc** [comment]
I appreciate your help! I have had to deal with this internally a few times. But now it is in my court! Thanks for your help and quick response!

**Comment by eeintech** [comment]
No problem, good luck!
